
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 28 01:16:47 GMT 2015
//----------------------------------------------------

package Example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LBRACE = 2;
  public static final int COLON = 7;
  public static final int NUMBER = 12;
  public static final int TRUE = 8;
  public static final int NULL = 10;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int FALSE = 9;
  public static final int RBRACKET = 5;
  public static final int error = 1;
  public static final int COMMA = 6;
  public static final int LBRACKET = 4;
  public static final int RBRACE = 3;
}

